name: Build and Release Flutter App

on:
  push:
    tags:
      - 'v*'  # Trigger this action when a tag like v1.0.0 is pushed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: build/app/outputs/flutter-apk/app-release.apk