name: Flutter CI/CD

on:
  push:
    tags:
      - 'v*' # Trigger the workflow when a tag like v1.0.0 is pushed

jobs:
  build:
    name: Build Flutter App
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable' # Use the stable version of Flutter

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Build APK (Android)
      - name: Build APK
        run: flutter build apk --release

      # Step 5: Archive APK
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk